# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('histry_txt', models.CharField(max_length=100, verbose_name='执行说明')),
            ],
            options={
                'verbose_name': '历史信息',
                'verbose_name_plural': '历史信息',
            },
        ),
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.TextField(verbose_name='os')),
                ('cpu', models.TextField(verbose_name='cpu')),
                ('disk', models.TextField(verbose_name='disk')),
                ('mem', models.TextField(verbose_name='mem')),
                ('network', models.TextField(verbose_name='network')),
            ],
            options={
                'verbose_name': '主机详细信息',
                'verbose_name_plural': '主机详细信息',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('port', models.CharField(default='22', max_length=5, verbose_name='端口')),
                ('user', models.CharField(max_length=15, verbose_name='用户')),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=1, verbose_name='组状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
        migrations.CreateModel(
            name='Jifang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jifang_dizhi', models.CharField(max_length=20, verbose_name='机房')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
            },
        ),
        migrations.CreateModel(
            name='Upload_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('file', models.FileField(upload_to='./upload/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='User_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='组名')),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=1, verbose_name='组状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_super', models.CharField(choices=[('0', '普通用户组'), ('1', '管理组')], default='0', max_length=1, verbose_name='是否管理组')),
            ],
            options={
                'verbose_name': '用户组信息',
                'verbose_name_plural': '用户组信息',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=1, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.User_Groups', verbose_name='用户所属组')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='jifang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Jifang', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='cmdb.User_Groups', verbose_name='所属组'),
        ),
        migrations.AddField(
            model_name='host_info',
            name='Hosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Hosts'),
        ),
    ]
