# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_histry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Users', verbose_name='用户'),
        ),
    ]
